server:
   port: 8081
   servlet:
      context-path: /auth
spring:
   security:
      oauth2:
         client:
            registration:
               facebook:
                  clientId: 170275890917896
                  clientSecret: c7d2ad6f73f2b2678578f6a1ef339238
               github:
                  clientId: dea3155ea885cb49bd03
                  clientSecret: da6c657ff50cdbd4c3a27908fc9263ed392441cc
                  redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
